#!/usr/bin/env python3
# vim: ts=4:sw=4:et:cc=120

import asyncio
import sys
import types

import ace.env

if __name__ == "__main__":
    result = asyncio.get_event_loop().run_until_complete(
        ace.env.register_global_env(ace.env.ACEOperatingEnvironment()).execute()
    )
    sys.exit(0)  # TODO return 1 on failure
