#!/usr/bin/env python3
# vim: ts=4:sw=4:et:cc=120

import asyncio
import sys
import types

import ace.env

if __name__ == "__main__":
    ace.env.register_global_env(ace.env.ACEOperatingEnvironment())

    # execute command
    result = ace.env.get_env().execute()

    # this allows cli commands to optionally be defined async
    if isinstance(result, types.CoroutineType):
        asyncio.get_event_loop().run_until_complete(result)

    sys.exit(0)
