version: '3.8'
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always
        hostname: redis
        container_name: ace-redis
        networks:
            - ace

    database:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        hostname: database
        container_name: ace-database
        environment:
            POSTGRES_PASSWORD: example
        networks:
            - ace

    core:
        build:
            context: .
        image: ace2:latest
        ports:
            - "443:443"
        restart: always
        hostname: ace-core
        container_name: ace-core
        environment:
            - ACE_API_KEY
            - ACE_BASE_DIR=/opt/ace
            - ACE_DB
            - ACE_REDIS
            - ACE_STORAGE_ROOT
            - ACE_URI=https://ace/core
            - PORT=443
        networks:
            - ace

networks:
    ace:

